version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql-projetodifm
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: projetodifm
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql